package com.example.enums;

public enum ProfileStep {
    DONE,ENTER_NAME,ENTER_SURNAME, ENTER_PHONE,EDIT_NAME,EDIT_SURNAME,EDIT_PHONE, ENTER_REGION, ENTER_FROM_DISTRICT, ENTER_TO_DISTRICT, ENTER_PEOPLE_COUNT, EDIT_CAR_NUM
}
