package com.example.enums;

public enum ProfileStep {
    DONE,ENTER_NAME,ENTER_SURNAME, ENTER_PHONE,EDIT_NAME,EDIT_SURNAME,EDIT_PHONE, ENTER_REGION, ENTER_FROM_DISTRICT, ENTER_TO_DISTRICT, ENTER_PEOPLE_COUNT, ENTER_CAR_MODEL, ENTER_CAR_NUM, ENTER_ADDITIONAL_INFO, ENTER_OFFEN, ENTER_LOGIN, ENTER_PASSWORD, ENTER_DRIVER_PHONE, ENTER_SEARCH_DRIVER_PHONE, EDIT_CAR_NUM
}
